//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public long id { get; set; }
        public string Parrafo1 { get; set; }
        public string Parrafo2 { get; set; }
        public string Parrafo3 { get; set; }
        public string Parrafo4 { get; set; }
        public string Parrafo5 { get; set; }
        public string Parrafo6 { get; set; }
        public string Parrafo7 { get; set; }
        public string Parrafo8 { get; set; }
        public string Parrafo9 { get; set; }
        public string Parrafo10 { get; set; }
    }
}
