//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuota()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public long id { get; set; }
        public double MontoCapital { get; set; }
        public double MontoInteres { get; set; }
        public double MontoDescuento { get; set; }
        public System.DateTime FechaPagoProgramado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> DiasCuota { get; set; }
        public Nullable<int> SwGeneroProximaCuota { get; set; }
        public long idPrestamos { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
