//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garantia
    {
        public long id { get; set; }
        public string NombreGarantia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> PrecioGarantia { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public long idPrestamo { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
