//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbFinanciaCorpEntities : DbContext
    {
        public dbFinanciaCorpEntities()
            : base("name=dbFinanciaCorpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AperturaSistema> AperturaSistema { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<CalificacionCartera> CalificacionCartera { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<CuentaBancaria> CuentaBancaria { get; set; }
        public virtual DbSet<Cuota> Cuota { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EntidadFinanciera> EntidadFinanciera { get; set; }
        public virtual DbSet<Garantia> Garantia { get; set; }
        public virtual DbSet<HTransaccion> HTransaccion { get; set; }
        public virtual DbSet<Natural> Natural { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Prestamo> Prestamo { get; set; }
        public virtual DbSet<Rubro> Rubro { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<TbResumenPrestamo> TbResumenPrestamo { get; set; }
        public virtual DbSet<TipoDesembolso> TipoDesembolso { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<TransaccionCuenta> TransaccionCuenta { get; set; }
        public virtual DbSet<TransaccionCuentaBancaria> TransaccionCuentaBancaria { get; set; }
        public virtual DbSet<VclienteGeneral> VclienteGeneral { get; set; }
        public virtual DbSet<VCuentaBancaria> VCuentaBancaria { get; set; }
        public virtual DbSet<VCuentaBancariaTransaccion> VCuentaBancariaTransaccion { get; set; }
        public virtual DbSet<VGPrestamo> VGPrestamo { get; set; }
        public virtual DbSet<VistaCajaTransaccion> VistaCajaTransaccion { get; set; }
        public virtual DbSet<VMensajeria> VMensajeria { get; set; }
        public virtual DbSet<VPrestamoCuotaCalificacion> VPrestamoCuotaCalificacion { get; set; }
        public virtual DbSet<VPrestamoCuotaCalificacionEstadoCuotaCanceladas> VPrestamoCuotaCalificacionEstadoCuotaCanceladas { get; set; }
        public virtual DbSet<VPrestamoCuotaCalificacionEstadoCuotaPendiente> VPrestamoCuotaCalificacionEstadoCuotaPendiente { get; set; }
        public virtual DbSet<VPrestamoCuotas> VPrestamoCuotas { get; set; }
        public virtual DbSet<VPrestamoCuotasVigente> VPrestamoCuotasVigente { get; set; }
    
        public virtual int sp_IniciarBasededatos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_IniciarBasededatos");
        }
    }
}
