//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public long id { get; set; }
        public double Monto { get; set; }
        public System.DateTime FechaHoraPago { get; set; }
        public string Gloza { get; set; }
        public long idCuota { get; set; }
    
        public virtual Cuota Cuota { get; set; }
    }
}
