//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.Cuota = new HashSet<Cuota>();
            this.Garantia = new HashSet<Garantia>();
        }
    
        public long id { get; set; }
        public double Monto { get; set; }
        public Nullable<System.DateTime> FechaDesembolzo { get; set; }
        public double InteresMensual { get; set; }
        public double PlazoMeses { get; set; }
        public Nullable<int> EstadoPrestamo { get; set; }
        public long idcliente { get; set; }
        public long idEmpleado { get; set; }
        public long idCalificacionCArtera { get; set; }
        public Nullable<long> idtipoDesembolso { get; set; }
    
        public virtual CalificacionCartera CalificacionCartera { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuota> Cuota { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garantia> Garantia { get; set; }
        public virtual TipoDesembolso TipoDesembolso { get; set; }
    }
}
