//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionCuenta
    {
        public long id { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Gloza { get; set; }
        public string TipoTransaccion { get; set; }
        public long idCuenta { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
