//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public long id { get; set; }
        public double Monto { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string GlozaTransaccion { get; set; }
        public long idCaja { get; set; }
        public string TipoTransaccion { get; set; }
    
        public virtual Caja Caja { get; set; }
    }
}
