//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCuentaBancariaTransaccion
    {
        public long idtransaccionBancaria { get; set; }
        public string NombreEntidad { get; set; }
        public string NroCuenta { get; set; }
        public string NombrecompletoTitular1 { get; set; }
        public string NombreCompletoTitular2 { get; set; }
        public string Moneda { get; set; }
        public Nullable<System.DateTime> FechaTranscaccion { get; set; }
        public double Monto { get; set; }
        public string ResponsableTransaccion { get; set; }
        public string TipoTransaccion { get; set; }
        public string GlosaTransaccion { get; set; }
    }
}
