//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCajaTransaccion
    {
        public long idcaja { get; set; }
        public string NombreEmpleado { get; set; }
        public long idtransaccion { get; set; }
        public double Monto { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string GlozaTransaccion { get; set; }
        public string tipoTRansaccion { get; set; }
    }
}
