//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMensajeria
    {
        public long id { get; set; }
        public double Monto { get; set; }
        public Nullable<System.DateTime> FechaDesembolzo { get; set; }
        public double InteresMensual { get; set; }
        public double PlazoMeses { get; set; }
        public Nullable<int> EstadoPrestamo { get; set; }
        public long idcliente { get; set; }
        public string NombreCompletoCliente { get; set; }
        public long idEmpleado { get; set; }
        public long idCalificacionCArtera { get; set; }
        public string NombreCalificacionCArtera { get; set; }
        public Nullable<int> NroCuotasPendiente { get; set; }
        public Nullable<double> TotalMontoInteresPendiente { get; set; }
        public Nullable<int> NroCuotasPagadas { get; set; }
        public Nullable<double> TotalMontoInteresCancelado { get; set; }
        public string GararantiaDescripcion { get; set; }
        public Nullable<System.DateTime> FechaPagoCuota1erCuota { get; set; }
        public Nullable<System.DateTime> FechaPagoCuotaUltimaCuota { get; set; }
        public Nullable<double> TotalDeudaGeneral { get; set; }
        public string Telefono { get; set; }
        public string MensajeCobranza { get; set; }
    }
}
