//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPrestamoCuotaCalificacionEstadoCuotaPendiente
    {
        public long idprestamo { get; set; }
        public double Monto { get; set; }
        public Nullable<System.DateTime> FechaDesembolzo { get; set; }
        public double InteresMensual { get; set; }
        public double PlazoMeses { get; set; }
        public Nullable<int> EstadoPrestamo { get; set; }
        public long idcliente { get; set; }
        public string NombreCliente { get; set; }
        public string Telefono { get; set; }
        public Nullable<double> totalInteres { get; set; }
        public Nullable<int> NroCuota { get; set; }
        public string EstadoCuota { get; set; }
        public long idCalificacion { get; set; }
        public string NombreCalificacion { get; set; }
    }
}
