//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPrestamoCuotaCalificacion
    {
        public long idprestamo { get; set; }
        public double monto { get; set; }
        public Nullable<System.DateTime> FechaDesembolzo { get; set; }
        public string NombreCliente { get; set; }
        public string Telefono { get; set; }
        public string NombreCalificacion { get; set; }
        public int nroCuotaPendiente { get; set; }
        public double TotalInteresPendiente { get; set; }
        public int NroCuotaCancelada { get; set; }
        public double TotalInteresCAncelado { get; set; }
    }
}
