//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPrestamoCuotas
    {
        public string idprestamo { get; set; }
        public string monto { get; set; }
        public Nullable<System.DateTime> FechaDesembolzo { get; set; }
        public string interesMensual { get; set; }
        public double PlazoMeses { get; set; }
        public Nullable<int> EstadoPrestamo { get; set; }
        public string NombreCalificacion { get; set; }
        public long idcliente { get; set; }
        public string NombreCliente { get; set; }
        public string Genero { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string DocumentoIdentidad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<long> Nit { get; set; }
        public string NombreRubro { get; set; }
        public string NombreDepartamento { get; set; }
        public string NombreCiudad { get; set; }
        public long idcuota { get; set; }
        public double MontoCapitalCuota { get; set; }
        public double MontoInteres { get; set; }
        public double MontoDescuento { get; set; }
        public System.DateTime FechaPagoProgramado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<int> DiasCuota { get; set; }
        public Nullable<int> swGeneroProximaCuota { get; set; }
    }
}
